README.md, pom.xml, src/main/java/com/redhat/pantheon/servlet/AsciidocRenderingServlet.java, src/main/java/com/redhat/pantheon/servlet/ModuleRootQueryServlet.java, src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
Add a sample unit test for servlets using Junit 5, Mockito, and Sling's own mock libraries.
=> Sample unit test

.travis.yml, README.md, pom.xml, src/main/resources/apps/pantheon/modules/all/add.html
reinstate pom.xml options to deploy to sling using the PostServlet
add upload parameter to specify the mimetype for asciidoc modules
=> various fixes

README.md, pom.xml, src/main/java/com/redhat/pantheon/model/Module.java, src/main/java/com/redhat/pantheon/servlet/AsciidocContentRenderingServlet.java, src/main/java/com/redhat/pantheon/servlet/AsciidocRenderingServlet.java, src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
Add code coverage plugins and initial settings.
This should provide a report (non-binding initially) on how code coverate is impacted by each pull request.
=> Code coverage

pom.xml, src/main/java/com/redhat/pantheon/conf/LocalFileManagementService.java, src/main/java/com/redhat/pantheon/servlet/AsciidocRenderingServlet.java, src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
This remedies the mysterious 404 issue (a NPE that Sling was just swallowing) that Joseph uncovered when missing Red Hat templates and css.
=> Removing use of Optional class and adding appropriate null checks

src/test/java/com/redhat/pantheon/data/ModuleDataRetrieverTest.java, src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
Move a unit test to a different class as it was testing methods for the wrong class.
Also create a new unit test class for the `ModuleDataRetriever` class with some basic unit tests.
=> add unit tests and move others

frontend/src/app/index.tsx, frontend/src/app/module.tsx
-Search by pressing enter.
-Get source name from transientSourceName.
-Fix reference problem for Firefox.
-Make date human readable.
-Inform the user when there are no results from the search.
-Validate that name and file are not empty.
=> Address QA concerns

frontend/src/app/app.css, frontend/src/app/index.tsx, src/main/java/com/redhat/pantheon/data/ModuleDataRetriever.java, src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
This adds sorting and changes the table for the patternfly datalist component. Also did some cleanup recommended by the tslinter
=> Replace table with datalist & Sort using the backend

src/main/java/com/redhat/pantheon/servlet/BulkDeleteServlet.java, src/main/resources/apps/pantheon/modules/all/html.html
Address QA comments on Delete button submission exception when none of the modules is selected.
=> [CCS-2790] hide delete button when none of the modules is selected

frontend/package.json, frontend/src/app/__snapshots__/app.test.tsx.snap, frontend/src/app/app.css, frontend/src/app/app.test.tsx, frontend/src/app/app.tsx, frontend/src/app/components/Chrome/Chrome.tsx, frontend/src/app/components/Chrome/Header/Brand/Brand.tsx, frontend/src/app/components/Chrome/Header/Header.tsx, frontend/src/app/components/Chrome/Sidebar/Sidebar.tsx, frontend/src/app/components/Chrome/SubHeader/SubHeader.tsx, frontend/src/app/login.tsx, frontend/src/app/module.tsx, frontend/src/app/routes.tsx, frontend/src/app/search.tsx, frontend/src/index.tsx, frontend/webpack.prod.js, frontend/yarn.lock
- changed app/index to app/search
- Added sidebar, header and route components using https://github.com/seanforyou23/draftcab as starting point. 
- Using router-react-dom 5.0
- Now the search loads with the application.
- Will create different PR for tracking the user logged in work that Ben originally did for the previous header.
- removed unused deps.
=> Initial sidebar implementation

frontend/src/app/__snapshots__/app.test.tsx.snap, frontend/src/app/components/Chrome/Header/Brand/Brand.tsx, frontend/src/app/components/Chrome/Header/Header.tsx, frontend/src/app/routes.tsx, frontend/src/app/search.tsx
- Re-adds the login login that Ben created but into the Brand component in the Header.
- Added some labels for the pagination
- Some random linter fixes
=> Update Brand with login logic

frontend/src/app/login.tsx
Users can now type credentials followed by an Enter key press to log in, rather than needing to mouse click on the Login button.
=> Login enter key

uploader/setup.sh
bash script that installs pantheon push command
=> setup script to install pantheon.py

frontend/src/app/__snapshots__/app.test.tsx.snap, frontend/src/app/search.tsx
This fixes a little bug that displayed duplicate search instructions.
=> Remove extra alert

uploader/setup.sh
1. change PANTHEON_BIN to ~/bin
2. avoid using sudo in symlinking
=> update PANTHEON_BIN and avoid using sudo

src/main/java/com/redhat/pantheon/model/api/Accessor.java, src/main/java/com/redhat/pantheon/model/api/Mutator.java, src/main/java/com/redhat/pantheon/model/api/ResourceMember.java, src/main/java/com/redhat/pantheon/model/api/SlingResource.java, src/main/java/com/redhat/pantheon/model/api/SlingResourceAdapterFactory.java, src/main/java/com/redhat/pantheon/model/api/SlingResourceUtil.java, src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java, src/test/java/com/redhat/pantheon/model/api/SlingResourceTest.java, src/test/java/com/redhat/pantheon/model/api/SlingResourceUtilTest.java, src/test/java/com/redhat/pantheon/servlet/ServletUtilsTest.java
Refactor a few parts of the api (nothing that should change how it's used) and add more methods to the `SlingResource` class.
=> Sling model updates

src/main/java/com/redhat/pantheon/data/ModuleDataRetriever.java
Fixing the bug for the wildcard search
=> wildcard bug fix

src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, src/main/java/com/redhat/pantheon/servlet/AsciidocRenderingServlet.java, src/main/java/com/redhat/pantheon/servlet/ServletUtils.java, src/test/java/com/redhat/pantheon/asciidoctor/AsciidoctorServiceTest.java, src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java, src/test/java/com/redhat/pantheon/servlet/ServletUtilsTest.java
extract the html generation logic to an independent service
refactor the code for conciseness and readability
add a test for the new AsciidoctorService
=> Asciidoctor service

uploader/pantheon.py
- add docstrings to methods
- Refactor code
- Per discussion with Carlos, it's better to use glob's out of box behaviour when uploading everything under a subdirecory. User should use "subdir/**/*" instead of "subdir/*"
https://docs.python.org/3/library/glob.html
=> [CCS-2999] add support for subdir/*

frontend/src/app/Dropdown.test.tsx, frontend/src/app/Dropdown.tsx, frontend/src/app/Pagination.test.tsx, frontend/src/app/Pagination.tsx, frontend/src/app/__snapshots__/Dropdown.test.tsx.snap, frontend/src/app/__snapshots__/Pagination.test.tsx.snap, frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/search.test.tsx, frontend/src/app/search.tsx
Fixed the issue of refresh to the first page on a new search.
Also, added a custom pagination component.
=> ccs-2989 fix and pagination changes

uploader/pantheon.py
- exclude pantheon2.yml file from getting uploaded
- remove an unused method
=> [CCS-2999] exclude pantheon2.yml from getting uploaded

frontend/src/app/search.tsx
=> Update preview call in react for drafts

frontend/src/app/search.tsx, src/main/java/com/redhat/pantheon/model/module/Metadata.java, src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java, src/main/java/com/redhat/pantheon/servlet/ModuleRevisionUpload.java
create new module revision metadata field for upload date
fix non-working sorting by other fields
changed response code to 201 when creating a module vs updating
revert module jcr query to search accross all nodes
=> fix uploaded date module sorting

frontend/src/app/moduleDisplay.test.tsx, frontend/src/app/moduleDisplay.tsx, frontend/src/app/revisions.tsx
Fix for the date substring exception in dev and QA environments
=> Fix: substring in version date null case

frontend/src/app/__snapshots__/moduleDisplay.test.tsx.snap, frontend/src/app/__snapshots__/revisions.test.tsx.snap, frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/moduleDisplay.test.tsx, frontend/src/app/moduleDisplay.tsx, frontend/src/app/revisions.test.tsx, frontend/src/app/revisions.tsx, frontend/src/app/search.tsx
* this PR implements product info on module display
* it addresses test coverage
* and code fixes including black screen on module display
=> [CCS-2986] restore getMetadata

src/main/java/com/redhat/pantheon/conf/GlobalConfig.java, src/main/java/com/redhat/pantheon/model/QuerySingleResult.java, src/main/java/com/redhat/pantheon/servlet/AbstractJsonSingleQueryServlet.java, src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java, src/test/java/com/redhat/pantheon/servlet/ModuleJsonServletTest.java
Adds a new API /module/render - GET operation to render a Module data in JSON format
(The code is still in-progress)
ToDo - Add test coverage for the API
P.S. \o/ my 1st Pantheon2 PR - feel free to rip it apart :dagger:
=> [CCS-3004] Adds a new API for module rendering

frontend/src/app/__snapshots__/module.test.tsx.snap, frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/components/Chrome/Header/User.test.tsx, frontend/src/app/components/Chrome/Header/User.tsx, frontend/src/app/components/Chrome/Header/__snapshots__/User.test.tsx.snap, frontend/src/app/components/Chrome/Sidebar/NavLinks.tsx, frontend/src/app/module.test.tsx, frontend/src/app/module.tsx, frontend/src/app/moduleDisplay.test.tsx, frontend/src/app/product.tsx, frontend/src/app/productDetails.tsx, frontend/src/app/productListing.tsx, frontend/src/app/revisions.tsx, frontend/src/app/search.test.tsx, frontend/src/app/search.tsx
* move code to componentDidMount to optimize the performance
* add timeout and catch exceptions on fetch for search page
=> Search page fixes

frontend/src/app/__snapshots__/moduleDisplay.test.tsx.snap, frontend/src/app/moduleDisplay.tsx, frontend/src/app/revisions.tsx
Small tweak to some of the code committed by Ankit and Lisa yesterday. Working examples of `componentDidMount` and `.harray.json` techniques.
=> Remove initialLoad, introduce componentDidMount, call .harray

frontend/src/app/__snapshots__/revisions.test.tsx.snap, frontend/src/app/revisions.tsx
* Ensure Version selection is required in the Modal
* Ensure product display is updated after a successful form post action
* Add a space between alert message and Product name field
* Change "all fields are required." to "All fields are required."
=> Ccs 2976 edit metadata bugfixes

frontend/src/app/__snapshots__/versions.test.tsx.snap, frontend/src/app/productDetails.tsx, frontend/src/app/versions.test.tsx, frontend/src/app/versions.tsx
This branch addresses the alert message for product version field on the Modal.
=> [CCS-2976] bug fix for version field on alert messages

src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
This is a simple API property value improvement PR for:
- correcting the value sent on title
- correcting the module_url_fragment
has no effect on test coverage
=> Changes on module api

frontend/src/app/__snapshots__/productDetails.test.tsx.snap, frontend/src/app/productDetails.test.tsx, frontend/src/app/productDetails.tsx
It fixes a couple of issues on the breadcrumbs on productDetails. Now it allows users to go to product listing from productDetails.
=> fix breadcrumbs on products

frontend/src/app/__snapshots__/gitImport.test.tsx.snap, frontend/src/app/__snapshots__/login.test.tsx.snap, frontend/src/app/__snapshots__/module.test.tsx.snap, frontend/src/app/__snapshots__/product.test.tsx.snap, frontend/src/app/__snapshots__/productDetails.test.tsx.snap, frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/__snapshots__/versions.test.tsx.snap, frontend/src/app/app.css, frontend/src/app/components/Chrome/Sidebar/__snapshots__/Sidebar.test.tsx.snap, frontend/src/app/module.test.tsx, frontend/src/app/product.test.tsx, frontend/src/app/productDetails.test.tsx, frontend/src/app/productListing.tsx, frontend/src/app/search.test.tsx, frontend/yarn.lock
Updates to patternfly needed for some of the filter to work.
- Updated various dependencies.
- Added css I will use in a later PR.
- Removed some tests that are not doing anything and start failing after the component updates.
- Updated the productListing dropdown icon as It needs to be explicitly set in the newer version of the patternfly component.
=> Ccs 2966 prep

README.md, container/pantheon.yaml
Add documentation on how to run with podman using pods and an included Kubernetes pod definition.
=> Podman instructions

frontend/src/app/Dropdown.test.tsx, frontend/src/app/Pagination.test.tsx, frontend/src/app/TestResources.tsx, frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/app.tsx, frontend/src/app/components/Chrome/Header/Brand/Brand.test.tsx, frontend/src/app/components/Chrome/Header/BuildInfo.test.tsx, frontend/src/app/components/Chrome/Header/Header.tsx, frontend/src/app/components/Chrome/Header/User.test.tsx, frontend/src/app/components/Chrome/Sidebar/NavLinks.test.tsx, frontend/src/app/components/Chrome/Sidebar/NavLinks.tsx, frontend/src/app/components/Chrome/Sidebar/Sidebar.test.tsx, frontend/src/app/fetchMock.ts, frontend/src/app/gitImport.test.tsx, frontend/src/app/login.test.tsx, frontend/src/app/module.test.tsx, frontend/src/app/moduleDisplay.test.tsx, frontend/src/app/product.test.tsx, frontend/src/app/productDetails.test.tsx, frontend/src/app/productListing.test.tsx, frontend/src/app/routes.tsx, frontend/src/app/search.test.tsx, frontend/src/app/search.tsx, frontend/src/app/versions.test.tsx
Figured out how to mock `fetch` "properly" for tests (at least so that test output is cleaner).
Removed a bunch of useless semicolons.
=> UI Fixup 2

frontend/src/app/__snapshots__/search.test.tsx.snap, frontend/src/app/__snapshots__/searchFilter.test.tsx.snap, frontend/src/app/moduleDisplay.tsx, frontend/src/app/search.test.tsx, frontend/src/app/search.tsx, frontend/src/app/searchFilter.test.tsx, frontend/src/app/searchFilter.tsx, frontend/yarn.lock
Create a component for the search filter and use it for basic searching.
=> CCS-2966 - filter component

frontend/src/app/Constants.tsx, frontend/src/app/productDetails.tsx
Basically just includes the fix for CCS-3172, which is the infinitely-repeating network call on the Product Details page. Also introducing a new Constants file that we should start using, instead of hardcoding strings everywhere.
=> UI Fixup 3

pantheon-bundle/src/main/java/com/redhat/pantheon/sling/PantheonRepositoryInitializer.java, pantheon-bundle/src/test/java/com/redhat/pantheon/sling/PantheonRepositoryInitializerTest.java
=> reinstating the initialization of the SYNC_SERVICE_URL variable

pantheon-bundle/frontend/src/app/product.tsx, pantheon-bundle/frontend/src/app/productDetails.tsx, pantheon-bundle/frontend/src/app/versions.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/extension/ModulePostPublishHydraIntegration.java, pantheon-bundle/src/main/java/com/redhat/pantheon/extension/events/ModuleVersionPublishStateEvent.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleVersionUpload.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/PublishDraftVersion.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/UnpublishVersion.java, pantheon-bundle/src/main/resources/SLING-INF/users/users.json, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ModuleVersionUploadTest.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/PublishDraftVersionTest.java, pantheon-slingstart/src/main/provisioning/pantheon.txt, uploader/pantheon.py
Adding a new demo user: "author"
"author" is part of the pantheon-authors group and can write and upload documents, but cannot publish them, nor can it create products or product versions.
"demo" still exists and is now part of the pantheon-publishers group, which can perform any action in the system.
The UI experience for authors is that they get errors when attempting to perform forbidden actions, rather than hiding the forbidden UI widgets, so the experience is not ideal, but if we have an appetite for fixing that then it will have to come as a separate feature.
=> Author vs publisher security

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
Spent awhile trying to diagnose a phantom issue. Turns out it was just a corrupt `sling/` folder. Regardless, this tweak I made along the way makes the project 0.1% better, so why not merge it?
=> Trivial extraction of constants

pantheon-bundle/src/main/resources/SLING-INF/content/static/rhdocs.css
This PR includes two fixes:
- add delay in sending hydra messages
- fix broken overpass.css
=> replace broken overpass.css

tools/git2pantheon/git_uploader.go, tools/git2pantheon/git_uploader_test.go, tools/git2pantheon/main.go
Had to move 	flag.Parse() because of:
https://golang.org/doc/go1.13#testing
=> Update git2pantheon to read user & pass from environment

pantheon-bundle/src/main/resources/SLING-INF/content/static/asciidoctor.css, pantheon-bundle/src/main/resources/SLING-INF/content/static/rhdocs.css
This PR fixes the font issues for code blocks in rhdocs.css
It also updates asciidoctor.css with some improvements from mcaron.
=> rhdocs updates from mcaron

pantheon-bundle/frontend/src/app/components/Chrome/Header/User.tsx, pantheon-bundle/frontend/src/app/components/Chrome/Header/__snapshots__/User.test.tsx.snap
Adds a mostly non-functional dropdown to the header bar.
=> CCS-3281 - Help icon

README.md, pantheon-bundle/frontend/src/app/__snapshots__/versions.test.tsx.snap, pantheon-bundle/frontend/src/app/searchFilter.tsx, pantheon-bundle/frontend/src/app/versions.test.tsx, pantheon-bundle/frontend/src/app/versions.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/GetObjectByUUID.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/GetObjectByUUIDTest.java
Getting around our "200 maximum json result" limit for the product & productVersion dropdowns in module metadata.
=> Split products

pantheon-bundle/frontend/src/app/product.tsx
Adjusted indentation on this file so the changes look substantial but it's almost all whitespace. The only change is around line 152 which is the `dismissNotification` method. I just added an additional field to setState.
=> Making error dialog closeable

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_command-line-interface.adoc
new module - describe the CLI for Pantheon
included preliminary draft with instructions for using the Pantheon uploader via CLI
=> FCCEUD-25 CLI commands

pantheon-bundle/src/main/java/com/redhat/pantheon/extension/HydraIntegration.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
This PR updates the message we send to Hydra for unpublished events.
=> [CCS-2965] update unpublish event message

pantheon-bundle/frontend/src/app/components/Chrome/Sidebar/NavLinks.test.tsx, pantheon-bundle/frontend/src/app/components/Chrome/Sidebar/NavLinks.tsx, pantheon-bundle/frontend/src/app/components/Chrome/Sidebar/__snapshots__/NavLinks.test.tsx.snap
This PR removes the "New Module" link 
It also refactors the NavLinks code base.
=> Remove New Module link from the left nav

pantheon-bundle/frontend/src/app/search.tsx
This PR fixes the pagination issue on search page
=> fix pager issue

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java
This PR includes:
- backend changes to handle the new attributes(pantheonproduct, pantheonversion, pantheonupdateddate, pantheonpublisheddate) for module display on CP
=> [CCS-3384] add new variables for CP display [WIP]

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java
This PR fixes the attribute name so that it matches the rhdocs-template
=> fix attribute names

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_pantheon-user-interface.adoc
Preliminary draft of UI description per [JIRA FCCEUD-21](https://projects.engineering.redhat.com/browse/FCCEUD-21)
=> FCCEUD- 21 describe the Pantheon II User Interface

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/ProductVersion.java, pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/AsciidoctorServiceTest.java
This PR injects metadata values to the header section of the html
=> Ccs 3384 backend fixes2

pantheon-bundle/pom.xml, pantheon-bundle/src/main/java/com/redhat/pantheon/extension/HydraIntegration.java
=> Ccs 3445 failover connection

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/SlingModelAdapterFactory.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/WorkspaceChild.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Content.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Metadata.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Module.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/ModuleLocale.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/ModuleVersion.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/workspace/Workspace.java, pantheon-bundle/src/main/resources/SLING-INF/nodetypes/nodetypes.cnd, pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/AsciidoctorServiceTest.java, uploader/pantheon.py
This PR makes the following changes:
- adds a custom node type for repository: pant:bucket
- update uploader so that it adds standalongAttributeFile property for pantheon/bucket resource
=> Ccs 3469 uploader

uploader/pantheon.py
This PR fixes the scenario where attrubuteFile was not uploaded when resources section is not empty.
=> bug fix for attibuteFile not imported

uploader/pantheon.py
a bug fix to address Git Import feature
=> Ccs 3469 uploader bugfixes2

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_comparison-between-modules-and-DITA-topics.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_what-is-a-module.adoc
Issue ID: FCCEUD-29
Issue Link: https://projects.engineering.redhat.com/browse/FCCEUD-29
In con_comparison-between-modules-and-DITA-topics.adoc:
* Remove -include::../attributes.adoc[]
* Remove 'topic' at the end of the first sentence
* Capitalize one instance of 'xml'
In con_what-is-a-module.adoc:
* Remove - include::../attributes.adoc[]
=> FCCEUD-29: REVIEW - amehende

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/AbstractJsonPostOrPutServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/StatusAcknowledgeServlet.java
Extract a servlet capable of parsing the request's body as a Json object. This should encapsulate the json parsing logic in a single place, allowing extending classes to focus (a bit more) on business logic.
=> extract an abstract json processing servlet for POST and PUT operations

uploader/pantheon.py
changes corresponding to new jcr cannonical structure
=>  changes corresponding to new jcr cannonical structure

uploader/pantheon.py
added small changes to upload all type of variants,
=>  multi variant upload enabled

uploader/pantheon.py
QA feedback, validation on variant :new jcr changes
=> Ccs 3597 modules jcr changes

pantheon-bundle/src/main/java/com/redhat/pantheon/sling/upgrade/PantheonUpgrader.java, pantheon-bundle/src/main/java/com/redhat/pantheon/sling/upgrade/impl/IntroduceModuleVariantRepositories.java, pantheon-bundle/src/main/java/com/redhat/pantheon/sling/upgrade/impl/RefactorModulesForVariants.java
Also add some logging lines to the upgrades.
=> fix workspace upgrade as it was using 'variants' instead of 'module_variants'

pantheon-karaf-feature/src/main/feature/feature.xml
Permissions updated from the main branch
=> update pantheon feature with latest permissions

pantheon-bundle/frontend/src/app/moduleDisplay.test.tsx, pantheon-bundle/frontend/src/app/moduleDisplay.tsx, pantheon-bundle/frontend/src/app/versions.test.tsx, pantheon-bundle/frontend/src/app/versions.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, pantheon-bundle/src/main/java/com/redhat/pantheon/extension/HydraIntegration.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/SlingModelAdapterFactory.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/VariantJsonServletTest.java
This PR fixes 2 things:
* populate default ack_status for moduleVersion. As status-user can't crate node. it can only update ack_status node
* pass in variant name to portal view uri
=> create default ack_status node for moduleVersion. update portal view url

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_previewing-modules-in-pantheon.adoc
Issue ID: FCCEUD-28
Issue Link: https://projects.engineering.redhat.com/browse/FCCEUD-28
* Create module "Previewing modules in pantheon"
=> FCCEUD-28: Describe how to view a rendered preview of a module

pantheon-bundle/src/main/resources/SLING-INF/content/docs/attributes.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_publishing-a-module-in-pantheon.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_unpublishing-a-module-in-pantheon.adoc
Issue ID: FCCEUD-27
Issue Link: https://projects.engineering.redhat.com/browse/FCCEUD-27
* Create module "Publishing a module in Pantheon"
=> FCCEUD-27: Describe how to publish a module

pantheon-bundle/pom.xml, pantheon-karaf-dist/pom.xml, pantheon-karaf-feature/pom.xml, pantheon-karaf-feature/src/main/feature/feature.xml, scripts/deploy_local.sh, scripts/pantheon_karaf.exports
This PR:
- Starts the karaf instance from target/assembly
- Updates the mongodb env variable name
- removes dependency on jitpack and uses apache maven repo
=> Cosmetic changes for deployment preparations

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_module-metadata-in-pantheon.adoc
* Create module "Module metadata in Pantheon"
=> FCCEUD-18: Describe module metadata

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java, pantheon-bundle/src/main/java/com/redhat/pantheon/helper/Symlinks.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assets/ImageServletFilter.java, pantheon-bundle/src/test/java/com/redhat/pantheon/helper/SymlinksTest.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assets/ImageServletFilterTest.java
Resulting in QA feedback from CCS-3558
=> Adds ability for symlinks to ignore extra slashes

pantheon-bundle/src/main/resources/SLING-INF/content/docs/attributes.adoc
updating the ProductUrl field in the Attributes file to the pantheon.corp.redhat.com address
=> update ProductUrl in  Attributes file

README.md
Updated the instructions for requesting a tech review as follows - 
* Changed the review group to @redhataccess/eud-tech-review
* Clarified a point of confusion around a 'Request review' button
=> Updated the instructions for requesting tech review.

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
=> Fixing search variant always being 1st variant which may not be canonical

pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/Child.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/util/ResourceTraversal.java, pantheon-bundle/src/test/java/com/redhat/pantheon/model/api/util/ResourceTraversalTest.java
turned it into a functional interface
=> minor improvements to the ResourceTraversal api

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc
Added the three remaining modules for our first release to the main Pantheon help document.
The only changes made are to change commented-out includes into actual modules.
=> WIP - Added three modules to the main Pantheon help document.

pantheon-karaf-feature/src/main/feature/feature.xml, uploader/pantheon.py
revert: ACL for demo user to add childs
=> revert: ACL for demo user to add childs 

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java, pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/ModuleMetadataExtractorTreeProcessorTest.java
This PR updates term: pantheon:abstract to system:abstract per Dawn.
=> update term to system:abstract per the Assembly Committee

uploader/pantheon.py
This PR adds logic to:
- Check whether variant and workspace has been created successful.
- If create variant or workspace have not succeeded, then exit with error message. Since, creation of workspace and variant are the first operations, if it does not succeed, uploader would exit.
=> CCS-3718: Intermittent 500 Server error for module variants while uploading using git import

pantheon-bundle/src/main/java/com/redhat/pantheon/jcr/JcrResources.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/Field.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/FieldImpl.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ServletUtils.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVersionUpload.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleVersionUpload.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ServletUtilsTest.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleVersionUploadTest.java
a. Use InputStreams when dealing with content
b. restore the checksum validation to prevent unnecesary load on the JCR repository if there are no changes
=> improve management of resources during uploads

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyJsonServlet.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assembly/AssemblyJsonServletTest.java
This PR adds:
- URL for assembly data
- Response for assembly data identified by assembly uuid and variant 
Sample response has been attached to the corresponding JIRA ticket.
=> CCS-3661: Json API for assembly

pantheon-bundle/frontend/src/app/versions.tsx
only add urlFragment when it's filledout
=> CCS-3457-vanityUrl_fixes

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyJsonServlet.java
Adds description field by mapping it to data in abstract.
=> CCS-3661: Json API for assembly. QA changes

pantheon-bundle/frontend/src/app/versions.tsx
add required warning message back
=> CCS-3333-assembly_metadata_fixes

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServlet.java, pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServletTest.java
This PR provides:
1. Variant based URI for Assembly - /api/assembly/variant.json/${variantUuid}
2. The data is same as that available on the corresponding JIRA.
=> CCS-3661: Json API for assembly. Adding variant based API

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/assembly/AssemblyPage.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/assembly/TableOfContents.java, pantheon-bundle/src/test/java/com/redhat/pantheon/model/AssemblyVersionTest.java
Fixed the bug that @noopurmath3 found at https://projects.engineering.redhat.com/browse/CCS-3312?focusedCommentId=2813181&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2813181
=> doc-level leveloffset is now accounted for

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc
* Create a procedure module for assigning metadata to a module
=> Describe how to assign module metadata

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc
Resolves: https://projects.engineering.redhat.com/browse/FCCEUD-39
@redhataccess/pantheon-developers Please review for technical completeness and accuracy.
=> Update title and introduction of main Pantheon help assembly

pantheon-bundle/frontend/src/app/__snapshots__/product.test.tsx.snap, pantheon-bundle/frontend/src/app/product.tsx, pantheon-bundle/frontend/src/app/productDetails.tsx
This  PR adds string input validation for urlFragment. It will only allow alphanumic, - and _ as valid input for urlFragment.
=> Ccs 3453 module assembly relationship fixes

pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/VariantJsonServletTest.java
=> CCS-3780: Create a New API for "Included in Guides". For test case

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java
This PR reverted a change in SlingResourceIncludeProcessor
=> Ccs 3453 module assembly relationship fixes2

pantheon-bundle/frontend/src/app/__snapshots__/search.test.tsx.snap, pantheon-bundle/frontend/src/app/__snapshots__/searchFilter.test.tsx.snap, pantheon-bundle/frontend/src/app/components/Chrome/Sidebar/NavLinks.tsx, pantheon-bundle/frontend/src/app/components/Chrome/Sidebar/__snapshots__/NavLinks.test.tsx.snap, pantheon-bundle/frontend/src/app/search.tsx, pantheon-bundle/frontend/src/app/searchFilter.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
* Change the label "Modules" to "Contents"  on the left nav
* Change the label "Module Type" to "Content Type" on the search results
* Add "Assembly" to the filter for better find ability
=> CCS-3743 - update labels on left nav and search results. add Assembly to the filter

pantheon-bundle/frontend/src/app/__snapshots__/search.test.tsx.snap, pantheon-bundle/frontend/src/app/search.test.tsx, pantheon-bundle/frontend/src/app/search.tsx
this ticket removes the checkboxes and Delete functionaltiy from the search page.
=> remove checkboxes and delete functionality

pantheon2.yml
Added a Pantheon configuration file so that the end-user documentation team can import the content they are creating into Pantheon and start reviewing it in its intended format.
=> Added a pantheon2.yml file to manage the end-user documentation.

pantheon-bundle/frontend/src/web-assets/dev-preview/ascii-doc-styleguide.html, pantheon-bundle/frontend/src/web-assets/dev-preview/assembly_access-control-list.html, pantheon-bundle/frontend/src/web-assets/package.json, pantheon-bundle/frontend/src/web-assets/yarn.lock, pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/document.html.haml
Since the &lt;head> tag isn't brought into prod just adding JS to add attribute that allows warning
Updated version of cp-documentation in web-assets build
=> CCS-3723: Adding inline JS to enable warning message for inline styles

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java, pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/ModuleMetadataExtractorTreeProcessorTest.java
Switching from `system:abstract` to `_abstract`
=> Changing abstract label text

pantheon-bundle/frontend/src/app/moduleDisplay.tsx
=> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up. Updating for the changes in master.

pantheon-karaf-feature/pom.xml, sling-org-apache-sling-karaf-configs/pom.xml, sling-org-apache-sling-karaf-features/pom.xml
=> Fix missing build deb

pantheon-karaf-feature/pom.xml, pantheon-karaf-feature/src/main/feature/feature.xml, sling-org-apache-sling-karaf-configs/pom.xml, sling-org-apache-sling-karaf-features/pom.xml
Lower to 0.1.1 due to some deps missing 0.1.2 which causes new builds to fail.
=> Lower to 0.1.1 due to some deps missing 0.1.2

pantheon-bundle/src/main/resources/SLING-INF/content/docs/attributes.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_user-roles-in-pantheon.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_user-roles.adoc
* Create a concept module User roles in Pantheon
=> FCCEUD-33: Describe roles

pantheon-bundle/frontend/spandx.config.js
=> Make React Spandx Config support local env file

pantheon-bundle/frontend/src/app/assemblyDisplay.tsx, pantheon-bundle/frontend/src/app/moduleDisplay.tsx, pantheon-bundle/frontend/src/app/versions.tsx
This PR:
1. Raises event when the publish/unpublish happens (in versions component)
2. Handles the event in module display and assembly display componnets
3. If event is publish, calls the API endpoint to get the URL.
4. If the response is not empty, set the URL
5. If the response is empty, construct the url on the client side.
=> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up.

pantheon-bundle/frontend/src/app/assemblyDisplay.tsx, pantheon-bundle/frontend/src/app/moduleDisplay.tsx
This PR fixes locale name in assembly details page.
=> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up. Locale fix

pantheon-bundle/frontend/src/app/assemblyDisplay.tsx, pantheon-bundle/frontend/src/app/moduleDisplay.tsx
This PR fixes issue with searchpage change
=> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up. Page traverse fix

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentMetadata.java, pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentVariant.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVersionUpload.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleVersionUpload.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/ServletHelper.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/VersionUploadHelper.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/VersionUploadOperation.java
Several parts to this PR:
- Start recording dates on metadata properly
- Reintroduce copying metadata from released version onto draft version
- Refactor version upload servlets to share common code
=> Fix publish/updated dates CCS-3877 CCS-3879

pantheon-bundle/frontend/src/app/versions.test.tsx, pantheon-bundle/frontend/src/app/versions.tsx
this PR made the following changes:
* fix showMetadataAlertIcon issue
* fix metadata population on draft version
=> CCS-3891-metadata_bugfix

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java, pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/document.html.haml
This PR injects an environment variable as an asciidoctor variable that the haml can key off of.
=> customer rendering based off environment variable

pantheon-bundle/frontend/src/app/searchResults.tsx
This PR fixes the url to module/assembly detail page
=> search beta fixes

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
This PR fixes a jackrabbit exception when a repository name contains space
=> Search Beta fixes2

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-configuring-repository.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/attributes.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_pantheon_yaml_file.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_config_repo.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_creating-a-product.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_versioning_a_product.adoc
Created a new assembly for the configuration section, and added the assembly to the master file. Made some minor edits to the module files as well.
=> FCCEUD-49 Added `assembly-configuring-repository.adoc`

pantheon2.yml
* con_pantheon.adoc
* con_user-roles.adoc
* proc_versioning_a_product.adoc
=> Added three new modules to the pantheon2.yml file:

pantheon-bundle/frontend/src/app/__snapshots__/product.test.tsx.snap, pantheon-bundle/frontend/src/app/product.test.tsx, pantheon-bundle/frontend/src/app/product.tsx
Refactor `product.tsx`. It is now a functional component
=> Ccs 3992 product tsx refactor

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-preparing-content-for-publication.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_previewing-modules-in-pantheon.adoc
* Create an assembly Preparing content for publication assembly
=> FCCEUD-45: Create the Preparing content for publication assembly

pantheon-bundle/pom.xml, pantheon-bundle/src/main/java/com/redhat/pantheon/helper/PantheonConstants.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/sitemap/SiteMapServlet.java
This PR introduces sitemap for the following resources:
- assembly (/api/sitemap/assembly.sitemap.xml)
- module (/api/sitemap/module.sitemap.xml)
=> Ccs 3993 sitemap

pantheon2.yml
This pull requests adds three assemblies and their constituent modules to the pantheon2.yml file for the repository so that they can be imported into Pantheon V2.
=> Added three assemblies and their modules to the pantheon2.yml file.

pantheon-bundle/frontend/src/app/__snapshots__/searchBeta.test.tsx.snap, pantheon-bundle/frontend/src/app/app.css, pantheon-bundle/frontend/src/app/searchBeta.tsx
=> CCS-4192-search-beta-build-date

pantheon-bundle/src/main/java/com/redhat/pantheon/helper/Symlinks.java
In troubleshooting an EUD issue, I discovered that the way that sling handles the combination of "working symlink to parent folder" and "missing ultimate file target" is unintuitive and our code hadn't previously handled that scenario well. This is a hopeful attempt to fix that.
=> CCS-3917 Tweaking symlink logic

pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/ServletHelper.java
This PR introduces two more attributes in the api for Customer Portal to consume. 
- relative_url
- pantheon_env
=> CCS-4190 add relative_url and pantheon_env to module/assembly api

pantheon-bundle/frontend/src/app/searchResults.tsx
This PR displays the modules/assemblies by update date in descending order on the search page
=> CCS-3725-sortByupdateDate

pantheon-bundle/frontend/src/app/__snapshots__/search.test.tsx.snap, pantheon-bundle/frontend/src/app/app.css, pantheon-bundle/frontend/src/app/search.tsx
add scroll to repo list in filter by repo section so repos don't extend to the bottom of search page
fix bug that cause checked repo to uncheck when remove filter input
=> CCS-4256-filter-by-repo-cleanup

pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java
This PR addresses the basic auth request issue for git2pantheon import
=> CCS-4142-SSO-integration-fixes 

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-configuring-repository.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-overview-of-modules.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-preparing-content-for-publication.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-searching-modules.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-setting-up-tools.adoc
* Add context variable to assemblies
* Add header and footer for declaring and undeclaring parent context
=> FCCEUD-52: Add context variables to assemblies

pantheon-bundle/frontend/src/app/components/Chrome/Header/User.tsx, pantheon-bundle/frontend/src/app/components/Chrome/Header/__snapshots__/User.test.tsx.snap, pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java
Revert login and logout enhancement. It breaks the session.
=> CCS-4249-SSO_enhancement_revert

pantheon-bundle/frontend/src/app/Dropdown.tsx
This PR removes the extra dropdown option.
=> CCS-4269-Pager_bugfixes

pantheon-bundle/frontend/src/app/Dropdown.tsx, pantheon-bundle/frontend/src/app/__snapshots__/bulkOperationConfirmation.test.tsx.snap, pantheon-bundle/frontend/src/app/app.css, pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx, pantheon-bundle/frontend/src/app/search.tsx
This PR checks if users try to apply the same product/version to multiple repositories
=> Ccs 4269 bugfixes2

pantheon-bundle/frontend/src/app/search.tsx
- when user tries to bulk publish/unpublish docs from more than one repo, alert message appears
- add functionality so only one bulk operation confirmation can appear at a time
=> CCS-4271: bulk publish additions

pantheon-bundle/frontend/src/app/BulkOperationPublish.tsx, pantheon-bundle/frontend/src/app/search.tsx
- added some documentation
- removed excess variables and fns
- changed console.log message (for developer purposes only)
- fixed percentage value of titles succeeded for publish/unpublish operations
=> CCS-4271: publish/unpublish changes

pantheon-bundle/frontend/src/app/gitImport.tsx
This PR:
- Adds check for 400 code from /api/clone
- Updates the error message parsing
=> CCS-4343: Regression: Git import does not identify a wrong URL anymore.

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc
https://projects.engineering.redhat.com/projects/FCCEUD/issues/FCCEUD-55
=> FCCEUD-55 Add how to assign content type in Assigning Metadata

pantheon-bundle/frontend/src/app/versions.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
* update document display for xref validation to use tree view
* update module listing servlet due to recent jcr changes for xref validations
=> CCS-4274 UI update for xref validations

pantheon-bundle/frontend/src/app/search.tsx
This PR fixes enabling/disabling button issue on bulk operations
=> CCS-4348-buttons

pantheon-bundle/frontend/src/app/BulkPublishConfirmation.tsx, pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx
This PR adds n/a to empty list
=> CCS-4344-status_display

pantheon-bundle/frontend/src/app/ErrorBoundary.test.tsx, pantheon-bundle/frontend/src/app/ErrorBoundary.tsx, pantheon-bundle/frontend/src/app/routes.tsx
=> CCS-3982-implement-error-boundary

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-overview-of-modules.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_adding-module-types_to_modules_in_Pantheon.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_identifying-module-types.adoc
https://projects.engineering.redhat.com/browse/FCCEUD-54
=> FCCEUD-54 Update the module type identifiers

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
https://projects.engineering.redhat.com/browse/FCCEUD-15
=> FCCEUD-15 Describe assemblies

pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/DocumentPreviewFilter.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/VersionUploadOperation.java, pantheon-bundle/src/main/java/com/redhat/pantheon/validation/helper/XrefValidationHelper.java, pantheon-bundle/src/main/java/com/redhat/pantheon/validation/validators/XrefValidator.java
This PR fixes the null pointer exception in XrefValidationHelper
=> CCS-4351-bugfixes_NullPointerException

pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java, pantheon-bundle/src/main/java/com/redhat/pantheon/validation/helper/XrefValidationHelper.java
This PR introduces a client side workaround for keycloak integration where it failed to turn code into token. In the workaround, we will do 3 retries if previous attempt fails.
=> SSO socket timeout

pantheon2.yml
@redhataccess/pantheon-developers I forgot to add a new file to pantheon2.yml. This PR adds it.
If all looks well technically, please merge.
=> FCCEUD-6.1 Adding new module to pantheon2.yml

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc, pantheon2.yml
@redhataccess/pantheon-developers Please review and if all looks OK, please merge.
=> FCCEUD-54.1 Updated pantheon2.yml with filename change

pantheon-bundle/frontend/src/app/__snapshots__/contentDisplay.test.tsx.snap, pantheon-bundle/frontend/src/app/__snapshots__/searchResults.test.tsx.snap, pantheon-bundle/frontend/src/app/contentDisplay.test.tsx, pantheon-bundle/frontend/src/app/contentDisplay.tsx, pantheon-bundle/frontend/src/app/searchResults.tsx, pantheon-bundle/frontend/src/app/versions.test.tsx, pantheon-bundle/frontend/src/app/versions.tsx, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
Updates to the dates that are displayed in search results and in details pages.
=> CCS-3997 Frontend changes to dates

pantheon-bundle/frontend/src/app/bulkOperationConfirmation.test.tsx, pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx, pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
this PR address the following issue:
* bulk edit confirmation list contains file path from previous operations
=> Ccs 4383 bulk edit confirmation

pantheon-bundle/frontend/src/app/GitImportAlert.tsx, pantheon-bundle/frontend/src/app/app.tsx, pantheon-bundle/frontend/src/app/contexts/GitImportContext.tsx, pantheon-bundle/frontend/src/app/gitImport.test.tsx, pantheon-bundle/frontend/src/app/gitImport.tsx, pantheon-bundle/frontend/src/app/routes.tsx, pantheon-bundle/frontend/src/app/search.tsx
When user imports git repo, alert user if import has failed or was successful.
=> Ccs 3895 git import messaging

pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx, pantheon-bundle/frontend/src/app/search.tsx
=> CCS-4383_bugfixes

pantheon-bundle/frontend/src/app/contexts/GitImportContext.tsx
handle error when status key is returned for git import but no master branch exists
=> CCS-3895-git-import-messaging-update

pantheon-bundle/frontend/src/app/app.tsx, pantheon-bundle/frontend/src/app/routes.tsx
wrap git import in error boundary to handle multiple import errors
=> CCS-4430: implement error boundary for git import

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about_products.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_pantheon_yaml_file.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_user-roles.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_config_repo.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_creating-a-product.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_importing-content.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_previewing-modules-in-pantheon.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_publishing-content.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_submitting-documentation-feedback.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_unpublishing-content.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_versioning_a_product.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/ref_prerequisites.adoc
Summary of changes:
- Expands the headings
- Adds prerequisites
- Address formatting issues
[Feedback from the modularisation workshop](https://docs.google.com/document/d/1gNAinKfB1b4R4vXtPApAikrmiOACUxIL-go1y6nsN8Y/edit)
=> FCCEUD-59 Adress feedback from modularistaion workshop

pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/PantheonXrefProcessor.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/DocumentPreviewFilter.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/DocumentVariantRenderServlet.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/PublishDraftVersion.java, pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/VersionUploadOperation.java, pantheon-bundle/src/main/java/com/redhat/pantheon/validation/helper/XrefValidationHelper.java, pantheon-bundle/src/main/java/com/redhat/pantheon/validation/validators/XrefValidator.java
- Make helper class singleton for memory optimization
- Bug fix: NP check added to prevent NPE.
=> Xref validation

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-searching-modules.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc-search-keyword.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc-search-view-results.adoc
Resolves: https://projects.engineering.redhat.com/browse/FCCEUD-57  Updates Search instructions according to Ui.
=> FCCEUD-57: Review and align search instructions

scripts/populateDrupalCache.py
Added support for providing environment as argument to help testers/devs have it working on other environments.
Added print usages instructions for better understanding of script.
=> CCS-4453 - Improvement on existing code

pantheon-bundle/pom.xml, pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java, pantheon-karaf-feature/pom.xml
* add /static/rhdocs.css to skip-pattern
* increase retries
=> Ccs 4310 update filter

pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java, pantheon-karaf-feature/pom.xml
Need QA branch testing before merge into master
=> revert-CCS-4310-update-filter

pantheon-bundle/src/main/java/com/redhat/pantheon/auth/keycloak/KeycloakFilter.java
This PR introduces the follow change:
* redirect users to sso on /starter.html
=> CCS-4366-lock-down-basic-auth

pantheon-bundle/frontend/src/app/search.tsx
This PR fixes the wrong module/assembly count number in the bulk operations modal
=> CCS-4487-bulk-operations-confirmation-fixes

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_pantheon_yaml_file.adoc
=> FCCEUD-79 Updates to pantheon2.yml file configuration descriptions

pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-pantheon-help.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-snippets.adoc, pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_submitting-documentation-feedback.adoc, pantheon2.yml
Resolves https://issues.redhat.com/browse/FCCEUD-64.
=> FCCEUD-64 Added concept module explaining snippet support Pantheon 2.

pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-snippets.adoc
Added context to hyperlink so reader knows they are being taken to another document/site.
@noopurmath3 Please approve and you can merge this.
=> FCCEUD-64.1 Added context to hyperlink

pantheon-bundle/pom.xml
This PR updates apache common-text to 1.10.0
=> security patch
