- src/main/resources/SLING-INF/nodetypes/nodetypes.cnd
Modules will be a top level node with all metadata, and the
asciidoc file will be a sub-node of type nt:file
> small change to the nodetypes

- src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java
asciidoc includes don't work when including regular files (non-modules)
> fix: includes for non-module resources don't work

- pom.xml
- src/main/java/com/redhat/pantheon/model/Module.java
- src/main/java/com/redhat/pantheon/servlet/AsciidocContentRenderingServlet.java
- src/main/java/com/redhat/pantheon/servlet/AsciidocRenderingServlet.java
- src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
Enable the sling models functionality on this application. Also create an initial version of a Module model to statically map all the properties of modules from our model.
Models help by putting all mapping information (from JCR to java classes) into a single place. If adopted, no code should use the JCR or sling resource apis going forward.
> enable sling models and create a Module model

- src/main/java/com/redhat/pantheon/use/ModuleData.java
- src/main/resources/apps/pantheon/modules/all/html.html
- src/test/java/com/redhat/pantheon/servlet/AsciidocRenderingServletTest.java
Initial backend search, will build on top of this with a front-end framework next.
Note, I changed a few variables and methods to static to be able to grab the data from sly/htl at any point on  src/main/java/com/redhat/pantheon/use/ModuleData.java .
The javax.script.Bindings don't get passed down to the class when I create a new instance of the class, it looks like it they get populated at app start by sling. By making it static I make sure the bindings that populate the resolver variable at init() are are accessible when I do each search.
Simple test case added to build on top of it later too.
> Initial backend search in html

- src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java
Discovered that although direct includes worked (title -> module), indirect includes did not (title -> assembly -> module). This appears to fix it.
> Include fix

- frontend/src/app/index.tsx
This change takes in consideration all paths not just /modules/ when doing previews and uses the path as a key instead of the name.
This also opens previews in new tabs instead of taking the user outside of react.
> use path as key and open previews on new windows

- frontend/src/app/index.tsx
Month returns 0-11 not 1-12. Also Day is just the day of a the week (0-6) Date returns 1-31.
> Fix date string

- pom.xml
- src/main/java/com/redhat/pantheon/data/ModuleDataRetriever.java
- src/main/java/com/redhat/pantheon/jcr/JcrQueryHelper.java
- src/main/resources/SLING-INF/nodetypes/nodetypes.cnd
- src/test/java/com/redhat/pantheon/data/ModuleDataRetrieverTest.java
- src/test/java/com/redhat/pantheon/jcr/JcrQueryHelperTest.java
- src/test/resources/META-INF/MANIFEST.MF
Add the `JcrQueryHelper` class to help with JCR repository access (e.g. with utilities for pagination) and their corresponding unit tests.
Use an in-memory JCR repository for unit tests. This will represent a cost in terms of test startup time, but will increase the coverage and depth of the unit tests.
Modify the `ModuleDataRetreiver` class to use this new helper class.
> modularize access to the JCR repository

- .travis.yml
- pom.xml
Enable code coverage reports for javascript to be sent out to codecov. The coverage reports will now be cumulative (js + java). The front end's test phase has been enabled to run in maven's test phase.
Also corrected some indentation issues on the pom.xml file, which will make this change a bit ugly.
> add codecov reports for javascript sources

- frontend/src/app/__snapshots__/login.test.tsx.snap
- frontend/src/app/__snapshots__/module.test.tsx.snap
- frontend/src/app/app.css
- frontend/src/app/login.test.tsx
- frontend/src/app/login.tsx
- frontend/src/app/module.test.tsx
- frontend/src/app/module.tsx
- frontend/tslint.json
This PR adds the bullseye patternfly layout to the login and module pages. It also changes the text input on these pages for formgroups, this allows an user to click on the label and have the text input box focused automatically.
The blue highlight on the search was changed for a grayish color.
I also disabled the no-console tslint rule, while we are developing the console log is very helpful, when we have alerts boxes and upgrade this project to GA we should re-enable the rule.
> add pf4-layout to login and module & change highlight color on search

- src/main/java/com/redhat/pantheon/data/ModuleDataRetriever.java
- src/main/java/com/redhat/pantheon/sling/PantheonRepositoryInitializer.java
- src/test/java/com/redhat/pantheon/data/ModuleDataRetrieverTest.java
- uploader/pantheon.py
Enable the use of sandboxes by any registered pantheon user. Sandboxes will be hosted under the `/content/sandbox` path, and the uploader will force the sandbox name to be that of the authenticated user. e.g. `/content/sandbox/<username>`
The uploader adds a `--sandbox` parameter (or `-b` for short) which may be used to specify that a push goes to the sandbox. Example usage:
`pantheon push -b -u user -p password` 
This would execute a push to the user's sandbox located at `/content/sandbox/user`.
Additional changes in this revision:
Reduced the amount of logging done by the uploader (i.e. removed the logging of non-uploaded files)
Added terminal colors for certain log entries to easily determine where there is a problem.
What this pull request does not contain:
Currently there is no way …
> enable personal sandboxes for hosting content

- src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorPool.java
- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- src/main/java/com/redhat/pantheon/model/ModuleRevision.java
- src/main/java/com/redhat/pantheon/servlet/ModuleRevisionUpload.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessorTest.java
- src/test/java/com/redhat/pantheon/servlet/ModuleRevisionUploadTest.java
The metadata extractor is an asciidoctor extension which is capable of extracting metadata from the Asciidoctor AST. In this revision only title and abstract are extracted, and with limitations. The metadata extractor is called after each module revision creation.
This change also fixes a memory leak in the Asciidoctor pool.
> add a metadata extractor

- frontend/src/app/__snapshots__/search.test.tsx.snap
- frontend/src/app/search.tsx
Initial state of the page requires to have 25 records instead of 10
> Search results

- pom.xml
- src/main/java/com/redhat/pantheon/extension/Event.java
- src/main/java/com/redhat/pantheon/extension/EventJobConsumer.java
- src/main/java/com/redhat/pantheon/extension/EventProcessingExtension.java
- src/main/java/com/redhat/pantheon/extension/Events.java
- src/main/java/com/redhat/pantheon/extension/ModulePostPublishExtension.java
- src/main/java/com/redhat/pantheon/extension/ModulePostPublishJobConsumer.java
- src/main/java/com/redhat/pantheon/extension/events/ModuleRevisionPublished.java
- src/main/java/com/redhat/pantheon/extension/events/ModuleRevisionPublishedEvent.java
- src/main/java/com/redhat/pantheon/model/api/SlingResourceAdapterFactory.java
- src/main/java/com/redhat/pantheon/servlet/module/ReleaseDraftRevision.java
- src/test/java/com/redhat/pantheon/extension/EventJobConsumerTest.java
- src/test/java/com/redhat/pantheon/extension/EventsTest.java
- src/test/java/com/redhat/pantheon/servlet/module/ReleaseDraftRevisionTest.java
This enables the possibility to add extension points to the system in asynchronous fashion. There are two main components in the mechanism:
The `Events` class serves as the single place where to fire an event. Events are hardcoded into methods and other system components should use this class to fire events when appropriate. On the receiving end, there are `JobConsumer`s, which receive the events and process them. Events are placed in queues and JobConsumers are created for each one of these queues. There should be as many queues as JobConsumers are created. It is possible to create a single queue to process all events if desired.
The last layer is the `EventProcessingExtension`. This is an interface that should be implemented to process individual types of events. Aside from implementing …
> add an extension mechanism

- uploader/setup.sh
setup.sh was giving an error: 
"ln: failed to create symbolic link '/home/anarang/bin/pantheon': No such file or directory"
Added a code snippet to create ~/bin directory if it does not exist.
> adding a fix for uploader script installation

- tools/git2pantheon/Dockerfile
- tools/git2pantheon/git_uploader.go
- uploader/pantheon.py
Introduce an Environment variable that will supersede user configuration. This is intended to be used on Openshift and automated deployments where git2pantheon calls the uploader. This will ensure that git2pantheon and the uploader talk to the intended environment and will disregard the pantheon2.yml server configuration that an user might be using to test locally.
Proof that the code works:
Var not set:
```
$ python3 uploader/pantheon.py push -d ~/Development/adocs/ 
Could not find a valid config file(pantheon2.yml) in this directory; all files will be treated as resource uploads.
server http://localhost:8080 is not reachable
```
I set the variable:
```
$ export PANTHEON2_SERVER=coolbeans.redhat.com
```
Result with the variable set:
```
$ python3 uploader/pantheon.py push -d …
```
> Set server only if PANTHEON_SERVER ENVVAR is not set.

- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- src/main/java/com/redhat/pantheon/model/api/EnumField.java
- src/main/java/com/redhat/pantheon/model/api/Field.java
- src/main/java/com/redhat/pantheon/model/api/SlingResource.java
- src/main/java/com/redhat/pantheon/model/module/Metadata.java
- src/main/java/com/redhat/pantheon/model/module/ModuleType.java
- src/main/java/com/redhat/pantheon/servlet/ModuleRevisionUpload.java
- src/main/java/com/redhat/pantheon/servlet/module/ReleaseDraftRevision.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessorTest.java
- src/test/java/com/redhat/pantheon/model/api/SlingResourceTest.java
- src/test/java/com/redhat/pantheon/servlet/ModuleRevisionUploadTest.java
- src/test/java/com/redhat/pantheon/servlet/module/ReleaseDraftRevisionTest.java
Enables the extraction of additional pieces of metadata, most of them coming from the asciidoc content itself:
- Headline: Headline is the first second-level header in the asciidoc content (if present)
- Module type: A naming convention on the module file.
- Date published
Already present:
- Title
- Abstract: The first paragraph of text in the module.
> CCS-2975: asciidoc metadata

- pom.xml
- src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorLifecycle.java
This also upgrades the asciidoctor version to 2.0
The API changed a bit, and now the code has to explicitly refer to the `JRubyAsciidoctor` implementation (which is the same one it has been using all along) in order to run in the OSGI environment. There might be a better way to do it, but in the short term this change upgrades the system to the latest asciidoctor and asciidoctorj.
> upgrade the asciidoctorj version to 2.1.0

- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
Restricts certain type of content from being considered as a module's abstract.
> CCS-2975: restrict certain kinds of asciidoc blocks from being considered as a module's abstract

- src/main/java/com/redhat/pantheon/servlet/module/UnpublishRevision.java
- src/test/java/com/redhat/pantheon/servlet/module/UnpublishRevisionTest.java
This pull request sets the stage for module unpublishing. It offers an API to do an unpublish similar to the "publish" one. Once invoked, and only if there is a 'released' module revision, the system will unpublish the module and if there is no draft revision set, it will get the latest historical revision for the module and will make it the draft.
To invoke this API:
```
POST /module/path.adoc?:operation=pant:unpublish`
```
> CCS-2965: add an action for unpublishing modules

- src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java
- src/main/java/com/redhat/pantheon/asciidoctor/extension/ContentAbstractBlockProcessor.java
- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/ContentAbstractBlockProcessorTest.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessorTest.java
- src/test/java/com/redhat/pantheon/servlet/AsciidocContentRenderingServletTest.java
This change implements a more accurate way of identifying and extracting a module's abstract, relying on asciidoc's own syntax.
The approach requires the use of a single named attribute on any paragraph in the content to identify the abstract. The attribute's name is `pantheon:abstract` (clearly identifying the application and the purpose) to make sure writers are able to tell the platform where the metadata is without any room for ambiguity.
A sample usage for this would be:
```adoc
= Why using attributes to identify metadata is a good idea
[pantheon:abstract]
It's a good idea to use attributes to identify metadata in the content as it removes any ambiguity when comparing to a positional based approach.
```
> CCS-2975: replace module abstract extraction for an attribute-based approach

- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessorTest.java
Look deep into the node structure to find the right subtitle to use as headline. Previously the algorithm was only looking at first level nodes.
> CCS-2975: fix headline metadata extraction

- src/main/java/com/redhat/pantheon/servlet/BuildDateServlet.java
- src/test/java/com/redhat/pantheon/servlet/BuildDateServletTest.java
This is needed because of how we are setting proxies now on the builds internally.
> Use manually set COMMIT_HASH ENV and not the Openshift default one

- src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- src/main/java/com/redhat/pantheon/util/function/FunctionalUtils.java
- src/test/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessorTest.java
The `MetadataExtractorTreeProcessor` could throw an exception under certain conditions. In general, the underlying asciidoctor ruby implementation could throw exceptions when calling java methods which do not apply in certain situations (e.g. `getContext()`), instead of failing gracefully. This pull request accounts for that scenario.
> CCS-3176: Prevent generation errors when using one of Pantheon's custom extensions

- pantheon-slingstart/README.md
- pantheon-slingstart/pom.xml
add a reference to the original slingstart project from where the provisioning
model files where originally sourced, and add a default parameter when using
the sling maven plugin for developer clarity
> add slingstart documentation and references

- container/Dockerfile
- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorPool.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/ImageSrcTransformer.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/conf/GlobalConfig.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assets/ImageServletFilter.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/ImageSrcTransformerTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assets/ImageServletFilterTest.java
Create a static image delivery mechanism for proxies and edge platforms. The mechanism consists of two parts:
1. A re-encoding of all generated `<img>` tags in the generated html so that they refer to images in an absolute way. The resulting html will have image tags of the form:
`<img src="/imageassets/{unique image id}">` with `{unique image id}` being a url friendly string by which the image can be uniquely identified in the system.
2. A system endpoint capable of handling the requested image asset urls, decoding the unique identifier and serving the image properly.
This mechanism should allow the edge to detect calls to the unique prefix in the system and route them appropriately to pantheon for subsequent caching.
> CCS-3208: add a static image delivery mechanism

- pantheon-bundle/pom.xml
This changes are based on this doc:
https://sling.apache.org/documentation/bundles/content-loading-jcr-contentloader.html
I confirmed that when I re-installed the bundle the static file's dates were updated.
> Force the React files to be overwritten when deploying a new version

- tools/git2pantheon/main.go
- tools/git2pantheon/main_test.go
This follows the same method we are using for the pantheon2 backend.
> Check for COMMIT_HASH instead of OPENSHIFT specific ENV VAR

- pantheon-bundle/src/main/java/com/redhat/pantheon/conf/GlobalConfig.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ModuleJsonServletTest.java
- Changes the content type to `module`
This is done in accordance with Charle's comment - https://projects.engineering.redhat.com/browse/UNIFIED-5409?focusedCommentId=1974799&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1974799
- Adds a new field `status` which is defaulted to "published" - this field will be used to denote if a module is published or unpublished. The event can then be used by any system consuming with the enrichment API.
This was changed as per the discussions on Team Call date: 27th Nov 2019 (Please see docs tooling meeting notes)
> A few changes to module json enrichment

- pantheon-bundle/frontend/src/app/versions.tsx
- pantheon-bundle/src/main/java/com/redhat/pantheon/extension/ModulePostPublishHydraIntegration.java
* This PR adds a solr_command for Module post publish hydra integration. The text message now looks like this:
{"id": "http://llu.usersys.redhat.com:8080/api/module?locale=en-us&module_id=0e79fdb9-be17-4f61-bf01-1744268b4cea","solr_command":"index"}
it used to be:
{"id": "http://llu.usersys.redhat.com:8080/api/module?locale=en-us&module_id=0e79fdb9-be17-4f61-bf01-1744268b4cea"}
* It also fixes the "All fields are required" alert problem when changing Document Use Case option in Edit Metadata. Current in master branch, after initial update on 'Edit Metadata', if an authenticated user attempts to change the 'Document use case' option to something else, an alert for "All fields are required" pops up, which is a bug. 
* It also fixes the "View on  Customer Portal" url as well as "Copy …
> Ccs 2972 add solr command in messages

- pantheon-bundle/frontend/src/app/__snapshots__/searchFilter.test.tsx.snap
- pantheon-bundle/frontend/src/app/searchFilter.tsx
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleListingServlet.java
I am removing the search sorting by product. What we save in the metadata is just the uuid and we already can filter by product. This also fixes a bug with filtering by moduleType correctly.
> get moduleType metadata in query

- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/AbstractJsonSingleQueryServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ServletUtils.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ModuleJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ServletUtilsTest.java
Enable the use of BCP47 language tags to identify locales. This means that all servlet parameters accepting locale codes now also accept BCP47 language tags for better compatibility. This also means that whenever the system is returning a locale code, it will preferably return a language tag instead of a Java locale code.
> enable locale parsing by language tag

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/FieldImpl.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/sling/ServiceResourceResolverProvider.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/AsciidoctorServiceTest.java
This change fixes a bug where anonymous users may not generate a module's preview. Since adding automatic metadata extraction from the asciidoc content, the process which writes the metadata to the JCR tree was not given the right permissions. This change ensures that the whole asciidoc generation process uses a service level resource resolver and thus ensure the appropriate write access.
> bug fix: anonymous module rendering is not working

- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/extension/ModulePostPublishHydraIntegration.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ModuleJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/sling/PantheonRepositoryInitializerTest.java
This PR introduces two changes
* replace "solr_command: index" with "event:publish" in  messages to Hydra broker
* add "view_uri" in modules api for search integration.
> add view_uri to modules in portal

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/HtmlModulePostprocessor.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/html/Html.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/html/HtmlTest.java
In asciidoc, you can create a hyperlink based off of file paths. However, the link that asciidoctor creates may not reliably point to where the target document ultimately lives in Pantheon.
This PR introduces a mechanism to specify the target module via its Pantheon UUID.
Here is the traditional way of creating an xref in Pantheon:
`<</some/other/doc.adoc,Please click here!>>`
Here is the new mechanism that this PR introduces:
`<</some/other/doc.adoc,pass:[]Please click here!>>`
When compiled with vanilla asciidoctor, the rendered document will be unaffected by the commented UUID and the link will point to the original author-specific target. When compiled with Pantheon, Pantheon will attempt to resolve the UUID and overwrite the link target with the found module's resource path in …
> Asciidoc link/xref dereferencing

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java
- pantheon-bundle/src/main/resources/SLING-INF/nodetypes/nodetypes.cnd
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessorTest.java
- uploader/pantheon.py
Pantheon 2 and the accompanying uploader now both understand what symlinks are.
So if you have asciidoc with a line like this:
include::recursiveSymlink/recursiveSymlink/recursiveSymlink/include.adoc
...and a directory structure like this:
$ ls -l
recursiveSymlink -> .
include.adoc
master.adoc
...then you can upload via a simple "pantheon push" and both the upload and the preview will complete successfully.
(Previously, the uploader would have churned forever, uploading endless duplicate copies of files, and Pantheon 2 would have ultimately run out of disk space. This no longer happens.)
There is a change in uploader behavior as a result of this PR.
1. You no longer specify 'resources' in your repository. Everything that isn't a module is now a resource and is uploaded as such, to ensure …
> Symlinks support

- pantheon-bundle/frontend/src/app/versions.tsx
When the user does not specify keywords, they no longer see "undefined" show up in the field on the next page reload.
> Undefined keywords CCS-3367

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/EnumFieldImpl.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleVersionUpload.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/model/api/SlingModelsTest.java
Pantheon will now detect the `pantheon-module-type` property declared inside a module's content to extract the module type. Valid values for this property are `CONCEPT`, `PROCEDURE`, and `REFERENCE` (all in caps). Any other value will be ignored by Pantheon.
The existing file-name-convention-based logic remains as a backup. This means that pantheon will look at the property first, and if not present, only then will it look at the file name to determine the module type.
> CCS-3392: add logic to parse the module type from an asciidoc property

- uploader/pantheon.py
This PR addresses an uploader exception when the Resource section is listed with empty entries.
e.g
cat pantheon2.yml 
```
server: http://localhost:8080
repository: llu
followlinks: true
titles:
modules:
- docs/cmsfr-release-notes/topics/*.adoc
resources:
#- titles/**/images/*
```
> fix  python exception: 'NoneType' object is not iterable

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleVersionUpload.java
On uploading the adoc files multiple times, the module title remains the same now.
> CCS-3270: File name not displayed instead of the title in search results on uploading the module twice

- docs
Added a symlink to the docs folder to make it easier for writers to contribute.
> FCCEUD-26_doc_symlink

- tools/git2pantheon/git_uploader.go
- tools/git2pantheon/git_uploader_test.go
- uploader/pantheon.py
CCS-3436: Updates git2pantheon to pass down the server url to the uploader instead of handling that logic at the uploader level.
> CCS-3436: Updates git2pantheon to pass down the server url to the uploader.

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/PublishDraftVersion.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/PublishDraftVersionTest.java
Steps to test:
1. Upload a doc with content similar to this:
```
Pantheon attributes:
showtitle: {showtitle}
pantheonproduct: {pantheonproduct}
pantheonversion: {pantheonversion}
pantheonupdateddate: {pantheonupdateddate}
pantheonpublisheddate: {pantheonpublisheddate}
```
2. Don't assign metadata
3. Preview the doc
4. Assign all necessary metadata
5. Publish the doc
6. View the rendered doc
Old behavior: variables are missing
New behavior: variables are available
> doc is now rebuilt immediately before sending publish event

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleVersionUpload.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ModuleVersionUploadTest.java
Upload a module with some asian characters to Pantheon and preview it. Prior to this, the encoding was messed up.
> Unicode file content is now handled properly

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Module.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/AbstractJsonSingleQueryServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ModuleJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/IncludedInAssembliesServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleVersionUpload.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/RelatedModuleServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleVersionUploadTest.java
Fixing up the existing module info servlet, and adding a dummy related module servlet, in order to unblock Drupal development. Since the related module servlet is a placeholder, no unit tests have been written. We can handle that once we implement the real logic.
> Drupal module apis

- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/helper/TransformToPojo.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/Acknowledgement.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Module.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/ModuleVersion.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/Status.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/StatusAcknowledgeServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/StatusAcknowledgementServletTest.java
This PR is for CCS-3494. It implements the following functionality:
- To make the API consistent the endpoint is be /api/status.
- The request would be POST and no path param would be needed.
- The request body would be: {"id":"$UUID", "status": "$status", "message": "Some helpful information", "sender": "hydra" }
- Saving of acknowledgement is supported, ATM, only for en_US locale
- The acknowledgement is saved as a node named status that would be sibling to metadata node.
- If a new request comes with same UUID, the existing node data would be updated.
>  CCS-3494: API endpoint for Hydra to send acknowledgement

- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/MockSlingHttpServletRequest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/StatusAcknowledgementServletTest.java
MockSlingHttpServletRequest does not support the some of the methods HttpServletRequest including but not limited to getUserPrincipal. This PR extends the existing MockSlingHttpServletRequest to override those methods. In this PR I have overridden getUserPrincipal. 
@xdavidson this would fix the test failures you are experiencing for https://github.com/redhataccess/pantheon/pull/271
> Custom MockSlingHttpServletRequest for the HttpServlet methods not supported by MockSlingHttpServletRequest

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/onetime/AckStatusCreateServlet.java
Designed to be called exactly once in our production environment and then removed later.
> Adding one-time ackStatus create servlet

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/CorsEnablingFilter.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/SimpleFilter.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/CorsEnablingFilterTest.java
This PR addresses the CORS issue CP raised against our API calls. It uses a SlingServletFilter to allow *.redhat.com to consume our api on GET/HEAD requests
> resolves CORS issue using Filter

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/Child.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/ChildImpl.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/util/SafeResourceTraversal.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/model/api/util/SafeResourceTraversalTest.java
Add a more compact null-safe way to traverse jcr structures using models.
This revision deprecates the existing `Child.map` method and adds a similar but more compact way to do complex JCR structure traversals and avoid `null` elements in the path. 
See the unit tests for the way to use it.
> add a more compact null-safe way to traverse jcr structures using models

- .travis.yml
- pantheon-karaf-feature/pom.xml
- scripts/deploy_local.sh
This PR is to update travis build to work with karaf distribution. The changes are:
-  Added JitPack based dependency to pantheon-karaf-feature to resolve org.apache.sling.karaf-configs
-  Added maven central repository to resolve maven-karf-plugin dependency
-  Udated travis-yaml to use customized settings.xml
-  Updated travis.yaml to output only error logs. This is to mitigate log exceeded maximum lines error.
>  CCS-3635:  Update travis build to work with karaf distribution

- uploader/pantheon.py
QA Comments for CCS 3600 fixes:
1.) When 'canonical' is missing from pantheon2.yml default value of canonical is set as True in the backend
2.) When value of canonical is blank in pantheon2.yml, 500 server error is displayed. Proper error message should be displayed instead
3.)  Value of canonical is saved as True in the backed, when its value is undefined in panthon2.yml
4.) Also observed that, when we try to upload the same repo twice, the last modified time is not updated.
5.) If a user does not update the pantheon2.yml (keeps it the previous format)  then he should get an error for missing fields which is not the case currently
> uploader validation QA comments

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assets/ImageServletFilter.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assets/ImageServletFilterTest.java
This tweaks our image servlet to be able to serve images that are resolved using symlinks.
I.e. if you have the following structure:
/images/whatever.png
/modules/mod.adoc
/modules/imglink -> ../images
And this in your mod.adoc:
image::imglink/whatever.png[]
Then this should now resolve correctly.
> Image symlinks

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/SlingPathSuffix.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/util/SlingPathSuffixTest.java
Add a utility for dealing with Sling path suffixes. In this revision the utility allows for template-based extraction of path parameters, enabling building complex, non-static API paths.
> sling servlet suffix utility

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/workspace/Workspace.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleVersionUpload.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleVersionUploadTest.java
Variant selected is either the first match if any variant definitions have the canonical flag set, otherwise it builds the "DEFAULT" variant for modules.
One thing this does NOT have is the logic to copy metadata from any old released version onto the draft version. Is that functionality we still want? @xdavidson @carlosmunoz
> Module uploads will now build canonical variant

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/SlingPathSuffix.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/util/SlingPathSuffixTest.java
Before this revision, the `SlingPathSuffix` class failed to recognize url sections after the path (e.g. query parameters). In this revision, the following two edge cases are resolved:
Suffixes with query parameters (e.g. `/path/example?q=a`)
Suffixes with client fragment (e.g. `/path/example#clientid`)
> remove edge cases from sling suffix analyzer

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/workspace/ModuleVariantDefinition.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/workspace/Workspace.java
Previously, trying to upload documents with an empty `variants` section of the pantheon2.yml file would result in 500 server errors for modules. This should fix that.
> fixing build-on-upload with no variants defined; CCS-3682

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/SlingPathSuffix.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/util/SlingPathSuffixTest.java
Return a map which can be resued without reparsing the whole suffix string.
> changes to the SlingPathSuffix to make it safer

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/ModuleMetadataExtractorTreeProcessorTest.java
This PR update the role name for pant:abstract. On metadata node, the abstract is stored as pant:abstract attribute
> update role name pant:abstract

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
UNIFIED-6570 is open for Hydra team to update the mapping on their end. Till then Hydra team expects module_uuid field in their mapping integration with search.
> Update varaint API to support field mapping on the hydra team

- tools/git2pantheon/git_uploader.go
- uploader/pantheon.py
This PR:
1. Logs  server, directory, and user being used for calling uploader in GoApp.
2. Checks whether error is null or not before logging error in GoApp.
3. Logs the response received from Pantheon in uploader so that GoApp can log the actual response text from pantheon rather than reason (OK/Internal Server Error etc.)
> CCS-3716: Add more logging for golang app

- pantheon-bundle/frontend/src/app/Constants.tsx
- pantheon-bundle/frontend/src/app/__snapshots__/versions.test.tsx.snap
- pantheon-bundle/frontend/src/app/assemblyDisplay.tsx
- pantheon-bundle/frontend/src/app/moduleDisplay.tsx
- pantheon-bundle/frontend/src/app/routes.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- pantheon-bundle/frontend/src/app/versions.tsx
-  a new route to /assembly
- a new route to /module
- assembly detail page that's a copy and past of module detail. The actual assembly detail page will be worked on i a separate ticket
-  add/edit assembly metadata
> Ccs 3333 assembly metadata

- pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/block_table.html.haml
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/AsciidocTest.java
Remove HAML flag that which causes an error when generating tables with empty cells.
The generated output of tables seems to be exactly the same (in terms of table structure)
as when generating a table with a {nbsp} cell.
> CCS-3186: tables with empty cells cause error when generating html

- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleVersionUploadTest.java
Reverts the disabling of locale based test cases.
> CCS-3763:  Build failure on OHC

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/Field.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleJsonServletTest.java
As a result the extracted abstract from the module content will be returned in the description field of the module API.
> use the abstract as the description in the module API

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/ModuleJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assembly/AssemblyJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/ModuleJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/VariantJsonServletTest.java
This change introduces a new `uuid` field in the module and assembly APIs which will contain the same value as the `module_uuid` and `assembly_uuid` respectively.
The previous fields are left in for backwards compatibility but are now deprecated.
> rename assembly_uuid and module_uuid to uuid

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
First iteration of the API.
It
1. Queries using the following XPath to get Assembly variants
`"/jcr:root/content/(repositories | assemblies | variants)//element(*, pant:assemblyVariant)[(released/content/*/@pant:moduleUuid='<uuid>')]"`
2. Iterates over the results and with each resource:
- Adapt to AssemblyVariant
- Get the Id
- Construct the url
- Get the title
> CCS-3780: "Included in guides" API

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/VariantJsonServletTest.java
* On module variant API, you will see "isPartOf" and the assembly/assemblies uuid and url that this module is included in
* On assembly variant API, you will see "hasPart" and the published module(s) info that this assembly includes
> Ccs 3703 schema support

- pantheon-bundle/frontend/src/app/__snapshots__/product.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/productDetails.test.tsx.snap
- pantheon-bundle/frontend/src/app/product.tsx
- pantheon-bundle/frontend/src/app/productDetails.tsx
Standardized references to 'UrlFragment' and 'Url Fragment' to 'URL Fragment' in accordance with style guide recommendations.
> Updated instances of 'UrlFragment' and 'Url Fragment' to 'URL Fragment'.

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/Content.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/EnumFieldImpl.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/ResourceDecorator.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/SlingModel.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/SlingResourceProxy.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/util/Memoizer.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/assembly/AssemblyPage.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/AckStatus.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/Document.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentLocale.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentMetadata.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentVariant.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/document/DocumentVersion.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/module/ModuleMetadata.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/workspace/WorkspaceChild.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/model/api/SlingModelsTest.java
This change alters the internal structure of the model object framework **without** changing the development API.
Changes include:
- Move all classes needed by the framework into the `model.api`package so it's self-contained.
- Simplify the resource proxy logic by eliminating a single logical path when translating method invocations.
- Move the `WorkspaceChild` class outside of the api package as it is a business class and not a framework one.
- Other minor refactorings.
> Minor refactorings

- pantheon-bundle/frontend/src/app/gitImport.tsx
- tools/git2pantheon/main.go
This PR
1. Parses the exception message coming from Git2Pantheon
2. Makes one of the left out error message into standard JSON error format.
> CCS-3785: error on git import when "Repository URL is invalid" needs to change on Pantheon UI

- pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/document.html.haml
This was supposed to be part of the original xref feature branch but somehow didn't make it into master.
> Reintroducing Wes' tweak to haml for anchors

- pantheon-bundle/src/main/java/com/redhat/pantheon/model/CustomModelAdapterFactory.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/model/api/SlingModelAdapterFactory.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/model/api/SlingModelAdapterFactoryTest.java
So that the actual model classes can be separated from the base class. This means the model classes can now be used completely independently from the rest of the source code.
> split the base model adapter factory and the custom implementation

- pantheon-karaf-feature/pom.xml
One of the poms was still referring to 0.1.1 rather than 0.1.0 which results in mvn test failing. This PR fixes that.
> mvn test issue fix

- pantheon-bundle/frontend/src/app/__snapshots__/searchFilter.test.tsx.snap
- pantheon-bundle/frontend/src/app/searchFilter.test.tsx
- pantheon-bundle/frontend/src/app/searchFilter.tsx
This PR updates the label in the sort filter. It changes the label from  "Module type" to "Content type" so that it matches the column name.
> Ccs 3743 change module type fixes

- pantheon-bundle/src/main/java/com/redhat/pantheon/extension/Events.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/extension/HydraIntegration.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/PublishDraftVersion.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/extension/EventsTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/assembly/AssemblyVariantJsonServletTest.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/module/VariantJsonServletTest.java
* remove deprecated "module_uuid", "variant_uuid" and "assembly_uuid" from module/assembly variant apis. Going forward, we will only have "uuid". Hydra team is aware of this action. They are going to prod with this change tomorrow.
* Update HydraIntegration to allow messages to be sent to Hydra when we publish/unpublish Assembly
> Ccs 3323 send assembly data

- pantheon-bundle/frontend/src/app/__snapshots__/moduleDisplay.test.tsx.snap
- pantheon-bundle/frontend/src/app/moduleDisplay.tsx
- pantheon-bundle/frontend/src/app/versions.test.tsx
- pantheon-bundle/frontend/src/app/versions.tsx
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/IncludedInAssembliesServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/module/VariantJsonServlet.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/ServletHelper.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/util/ServletHelperTest.java
- scripts/deploy_local.sh
This PR:
1. Introduces a new API endpoint /module/assemblies.json for retrieving list of assembly details corresponding to module variant uuid.
2. Refactors logic for retrieving list of assembly details corresponding to module into a set of utility methods.
3. Adds assembly list to the module details page where each assembly title links to assembly details page.
>  CCS-3480: Show assemblies on module detail page

- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/ServletUtils.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/ServletUtilsTest.java
This should fix the problem in #427 and still allow the api clients to use the encoding of their choice.
> fix the incorrect encoding of a stream parameter when a character encoding is specified

- pantheon-bundle/frontend/src/app/__snapshots__/assemblyDisplay.test.tsx.snap
- pantheon-bundle/frontend/src/app/assemblyDisplay.test.tsx
- pantheon-bundle/frontend/src/app/assemblyDisplay.tsx
- pantheon-bundle/frontend/src/app/moduleDisplay.tsx
- pantheon-bundle/src/main/java/com/redhat/pantheon/extension/url/CustomerPortalUrlProvider.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/sling/PantheonRepositoryInitializer.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/sling/PantheonRepositoryInitializerTest.java
ACL issues were causing QA to see partial URLs when calling APIs unauthenticated, this fixes it to read the value directly from the environment variable which is not ACL'ed.
> Reworking portal url handling

- pantheon-bundle/frontend/src/app/assemblyDisplay.tsx
- pantheon-bundle/frontend/src/app/moduleDisplay.tsx
This PR
- Calls the url provider endpoint from publish event handler in modules component.
- Adds a wait of 1 sec to the above call so that JCR changes are propagated. This is needed because even though publish endpoint sends 200, it takes nearly a second for changes to propagate in JCR structure.
> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up

- pantheon-bundle/frontend/src/app/moduleDisplay.tsx
This PR implements a non-elegent fix since useEffect hook cannot be used with class based components.
> CCS-3812: Module details page needs to be refreshed for the "View on portal" link to show-up. 

- pantheon-bundle/frontend/src/web-assets/dev-preview/ascii-doc-styleguide.html
- pantheon-bundle/frontend/src/web-assets/dev-preview/assembly_access-control-list.html
- pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/document.html.haml
JS for loading cp-documentation stopped working for some reason
CSS was moved to the web component folder and link needed to be changed here
rhdocs is necessary on a wrapper for no-JS version to be styled correctly
> CCS-3839: Fixing preview issues loading JS, CSS and styling page

- pantheon-karaf-feature/src/main/feature/feature.xml
- sling-org-apache-sling-karaf-features/pom.xml
Bump snapshot version for karaf features. This was meant to go along with the configs version but was missed.
> Bump features to 0.1.2

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/ServletHelper.java
This PR introduces "view_uri" in module variant api for included_in_guides. A feature requested by Wes for rendering documents on the Customer Portal side.
> add view_uri to included_in_guides

- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/util/ServletHelper.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/servlet/util/ServletHelperTest.java
This PR fixes the issue where included_in_guides has empty value when both draft and released versions are present.
> CCS-3849: Empty value in included_in_guides

- pantheon-bundle/frontend/src/app/versions.tsx
* fix empty metadata when there are both draft and published versions
* add ids to buttons for automation suite
> CCS-3891 - fix metadata display for draft and published

- pantheon-bundle/frontend/src/app/__snapshots__/product.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/productDetails.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/productListing.test.tsx.snap
- pantheon-bundle/frontend/src/app/app.css
- pantheon-bundle/frontend/src/app/contexts/ProductContext.tsx
- pantheon-bundle/frontend/src/app/modals/Product.ts
- pantheon-bundle/frontend/src/app/product.test.tsx
- pantheon-bundle/frontend/src/app/product.tsx
- pantheon-bundle/frontend/src/app/productDetails.test.tsx
- pantheon-bundle/frontend/src/app/productDetails.tsx
- pantheon-bundle/frontend/src/app/productListing.test.tsx
- pantheon-bundle/frontend/src/app/productListing.tsx
- pantheon-bundle/frontend/src/app/routes.tsx
- pantheon-bundle/src/main/resources/apps/pantheon/templates/haml/html5/document.html.haml
We now have the ability to press the back button from Product Details to return to Product Listings
- refactored `productDetails.tsx` and `productListing.tsx` so they are now functional components
- created `ProductContext` so `productDetails.tsx` and `productListing.tsx` can access all product info
> Ccs 3510 back button bug fix

- pantheon-bundle/frontend/src/app/contentDisplay.tsx
When refactoring `assemblyDisplay` into `contentDisplay`, a forward slash in creating a url was removed. This pr adds it back in.
> CCS-4004-view-published-assembly-fix

- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
Changing the system variable from `:pantheon-module-type:` to `:_module-type:` for consistency with other system keywords such as `[role=_abstract]`
> Renaming module type field

- pantheon-bundle/src/main/resources/SLING-INF/content/docs/assemblies/assembly-configuring-repository.adoc
Interestingly, this one-line change resolves an error running the AsciiDoctor command. Because this assembly does not render correctly in Pantheon V2 today, and this is the only difference I can see between this and other assemblies, my guess is that this will resolve that issue as well.
> Minor change to the "Configuring your repository" assembly.

- pantheon-bundle/frontend/src/app/components/Chrome/Header/User.tsx
- pantheon-bundle/frontend/src/app/components/Chrome/Header/__snapshots__/User.test.tsx.snap
- pantheon-bundle/frontend/yarn.lock
- pantheon-bundle/pom.xml
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/AsciidoctorService.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/PantheonXrefProcessor.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/SlingResourceIncludeProcessor.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/EndUserDocsFilter.java
- pantheon-bundle/src/main/java/com/redhat/pantheon/servlet/EndUserDocsServlet.java
- pantheon-karaf-feature/src/main/feature/feature.xml
- uploader/pantheon.py
Adding a couple classes to support rendering the special case of EUD docs, as well as tweaking some existing classes to help support EUD docs as well (for example, disabling xref processing). The logic checks to see if newer documents have been uploaded to /content/docs in the JCR, otherwise it falls back to the static help docs that were present when the pantheon bundle was built that are located in /content/staticdocs.
> CCS-3917 End User Docs

- pantheon-bundle/frontend/src/app/gitImport.tsx
- tools/git2pantheon/git_uploader.go
- tools/git2pantheon/main.go
This PR:
- Tweaks current go app to use the new [uploader|https://github.com/redhataccess/pantheon-uploader] file
- Change _const uploader_url =_ _"https://raw.githubusercontent.com/redhataccess/pantheon/master/uploader/pantheon.py"_ to _const uploader_url = "https://raw.githubusercontent.com/redhataccess/pantheon-uploader/master/pantheon_uploader/pantheon.py_"
- Consolidate existing Go app's APIs under /api
> CCS-4163: Use the new uploader in the existing git2pantheo

- pantheon-bundle/src/main/java/com/redhat/pantheon/helper/Symlinks.java
Our symlink logic introduces double-slashes into resource paths, and that was interfering with our check to see if the resource that was returned was the same one that we requested.
> CCS-4208 Fixing symlinks

- pantheon-bundle/src/main/resources/SLING-INF/content/docs/attributes.adoc
* Declared the attribute LinkToSearchPage with the present search page
url
> FCCEUD-53: Declare the :LinkToSearchPage: attribute

- pantheon-bundle/frontend/src/app/__snapshots__/bulkOperationMetadata.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/search.test.tsx.snap
- pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- pantheon-bundle/frontend/src/app/searchResults.tsx
This PR hide Edit metadata button when no documents are selected. This requires users to select documents before clicking on Edit Metadata button.
> CCS-4270-bulk_edit_metadata_bugfixes

- pantheon-bundle/frontend/src/app/BulkPublishConfirmation.tsx
- pantheon-bundle/frontend/src/app/__snapshots__/bulkOperationConfirmation.test.tsx.snap
- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx
This PR introduces two small changes:
1. update confirmation list to be an ordered list, which provides the item counts
2. fix non unique key warning for the List component
> change list to ordered list to show user item counts

- pantheon-bundle/frontend/src/app/__snapshots__/bulkOperationConfirmation.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/bulkOperationMetadata.test.tsx.snap
- pantheon-bundle/frontend/src/app/__snapshots__/search.test.tsx.snap
- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.test.tsx
- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx
- pantheon-bundle/frontend/src/app/bulkOperationMetadata.test.tsx
- pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- pantheon-bundle/frontend/src/app/searchResults.test.tsx
- pantheon-bundle/frontend/src/app/searchResults.tsx
This PR addresses the following issues:
- update the icon after bulk edit metadata
- fix the grayed out section after bulk edit metadata
- fix the double click issue when users attempt to bulk edit again after completes a previous bulk edit
> Ccs 4270 bulk edit metadata bugfixes

- README.md
https://projects.engineering.redhat.com/browse/FCCEUD-58
Contributing to Pantheon (https://github.com/redhataccess/pantheon) targets all contributors, but it currently includes some guidance that is clearly targeting FCCEUD contributors without including similar content for other contributors.
E.g. Prerequisites include the following line: You must be a member of the pantheon-doc-authors team in the redhataccess group in GitHub.
> WIP: FCCEUD-58 Update Contributing to Pantheon

- pantheon-bundle/frontend/src/app/BulkOperationPublish.test.tsx
- pantheon-bundle/frontend/src/app/BulkOperationPublish.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- enable check icon to be added or removed based on publish/unpublish operation
- user cannot publish titles from multiple repos. alert message will display and publish/unpublish buttons are disabled
- locale and variant form data are now appended once, not for each title being published
> CCS:42711: some bulk publish updates

- pantheon-bundle/frontend/src/app/search.tsx
previously when a user closed a publish/unpublish modal, and then tried to click another bulk operation button, they would have to click twice in order for the modal to appear. Now the button just needs one click
> bulk operation button double click fix

- pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
This PR fixes an UI issue that the confirmation was displayed after Cancel button was clicked.
> do not display confirmation when cancle button was clicked

- pantheon-bundle/frontend/src/app/BulkPublishConfirmation.tsx
- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx
This PR addresses a QA concern. 
* When the list is empty, render "n/a" 
* When list is not empty, render an ordered list
> CCS-4344-confirmation_updates

- pantheon-bundle/frontend/src/app/BulkOperationPublish.test.tsx
- pantheon-bundle/frontend/src/app/BulkOperationPublish.tsx
- pantheon-bundle/frontend/src/app/BulkPublishConfirmation.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- pantheon-bundle/frontend/src/app/searchResults.tsx
This PR address the following issues:
* when performance bulk publish/unpublish more than once on the same repo, the first click clears checkboxes selected
* when bulk publish multiple documents where one of them has missing metadata, published icons are not updated after the bulk operation completed
> CCS-4359-button_click_issues_on_republish

- pantheon-bundle/frontend/src/app/__snapshots__/contentDisplay.test.tsx.snap
- pantheon-bundle/frontend/src/app/contentDisplay.tsx
Pournima noted that "Module Type" and "First Publish Date" headers were out of alignment with their values. This fixes that.
> CCS-3997 Aligning dates on doc detail pages

- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.test.tsx
- pantheon-bundle/frontend/src/app/bulkOperationConfirmation.tsx
- pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
This PR changes how icons are repopulated after bulk editing. Like bulk publish/unpublish, after closing of the confirmation dialog, icons will be repopulated.
> repopulate icons after closing of confirmation

- pantheon-bundle/frontend/src/app/Pagination.test.tsx
- pantheon-bundle/frontend/src/app/Pagination.tsx
- pantheon-bundle/frontend/src/app/__snapshots__/searchResults.test.tsx.snap
- pantheon-bundle/frontend/src/app/searchResults.tsx
when user selects title in search results component and then navigates to the next page, their previous selection/s are cleared.
This PR fixes the issue for now of disabling the pagination once a title is selected.
> CCS-4347-handle-multiple-repo-selections

- pantheon-bundle/frontend/src/app/BulkOperationPublish.test.tsx
- pantheon-bundle/frontend/src/app/BulkOperationPublish.tsx
- pantheon-bundle/frontend/src/app/bulkOperationMetadata.tsx
- pantheon-bundle/frontend/src/app/search.tsx
- pantheon-bundle/frontend/src/app/searchResults.tsx
This PR addresses the following bulk republish issues:
* when user does bulk publish/unpublish over and over, the button click on Publish/Unpublish unselects the checkboxes
* when user does bulk unpublish over and over, the unpublish action does not happen
> CCS-4359_bugfixes

- pantheon-bundle/frontend/src/app/searchResults.tsx
fix so when a user selects number of results to display from pagination, the pagination is no longer disabled and user could move between pages
> CCS-4347: update to disabling pagination for search results

- pantheon-bundle/frontend/src/app/__snapshots__/contentDisplay.test.tsx.snap
- pantheon-bundle/frontend/src/app/contentDisplay.tsx
- pantheon-bundle/frontend/src/app/versions.test.tsx
- pantheon-bundle/frontend/src/app/versions.tsx
This PR addresses the following UI issues on Pre-live url:
* After publish/unpublish, it requires a page refresh to see Customer Portal Url/Pre-live  Url
* After modifying product version on a draft document, it requires a page fresh to see Pre-live url updated with the  new product verison fragment
> CCS-4183-bugfixes

- .gitignore
- pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java
- pantheon-bundle/src/test/java/com/redhat/pantheon/asciidoctor/extension/ModuleMetadataExtractorTreeProcessorTest.java
Because writers update most ADOC files and specify
the first para as the abstract, just use the first
para as the abstract if it is not explicitly specified.
>  feat: use first para as abstract

- pantheon-bundle/frontend/src/app/contentDisplay.tsx
This PR fixes a UI exception when pant:dateFirstPublished is missing on published documents before pant:dateFirstPublished was introduced.
> UI fix for datePublishDate and lastPublishDate

- pantheon-bundle/frontend/src/app/contentDisplay.tsx
- pantheon-bundle/frontend/src/app/versions.tsx
pant:dateFirestPublished was introduced a couple of months ago while we have documents published without that attribute. This PR fixes the display error when dateFirstPublished is missing on released metadata node.
> dateFirstPublsihed_UI_fixes

- .github/workflows/maven.yml
This PR removes the golang related github actions. We depreciated the golang tool a few months ago. And the golang tests returns errors during the build:
2021-08-16T09:01:36.7169944Z 09:01:36.716864 main.go:74: Invalid request method GET
2021-08-16T09:01:36.7170895Z {"error" : "Invalid request method"}
2021-08-16T09:01:36.7171408Z 
2021-08-16T09:01:36.7172231Z 09:01:36.716960 main.go:38: Error in unmarshalling request body unexpected end of JSON input
2021-08-16T09:01:36.7173345Z {"error" : "Error reading request body due to unexpected end of JSON input "}
2021-08-16T09:01:36.7174089Z 
2021-08-16T09:01:36.7174666Z 09:01:36.717109 main.go:45: repo:  test
2021-08-16T09:01:36.7175373Z 09:01:36.717124 main.go:46: branch: 
2021-08-16T09:01:36.7176149Z {"error" : "The repository entered does …
> clean up github actions

- pantheon-bundle/frontend/src/app/app.css
https://issues.redhat.com/browse/CCS-4579
Allow xref id's to wrap so they can be copied. I'm not sure how to get this UI for testing, but once it is you should be able to see the entire xref and it should be selectable/copyable.
Should look like this:
> CCS-4579: Allow xref-ids to wrap so they can be copied

- pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_assigning-metadata-to-a-module.adoc
This fixes a broken link from *8.1. Assigning metadata to content* to *4.3. Adding the module type to modules in Pantheon*.
> broken_link Fixing broken link to Adding module type
